// 0 = Paid
// 1 = to pay
// 2 = pending 
// 3 = Review
const orders = [ 
    {
        id: 1,
        name: 'Succulent Plant',
        cat:0,
        price: '75.99',
        quantity: '3',
        status: 'Pending',
        review: 'done',
        img: require('../../assets/images/succulent.png'),
        date:'10/04/2021',
    },
    {
        id: 2,
        name: 'Dragon Plant',
        cat:0,
        price: '29.99',
        quantity: '1',
        status: 'Pending',
        review: 'done',
        img: require('../../assets/images/dragon.png'),
        date:'5/02/2021',
    },
    {
        id: 3,
        name: 'Pothos Plant',
        cat:1,
        price: '51.98',
        quantity: '2',
        status: 'Paid',
        review: 'done',
        img: require('../../assets/images/money.png'),
        date:'5/02/2021',
    },
    {
        id: 4,
        name: 'Philodendron Plant',
        cat:1,
        price: '86.97',
        quantity: '3',
        status: 'Paid',
        review: 'done',
        img: require('../../assets/images/Philodendron.png'),
        date:'18/05/2021',
    },
    {
        id: 5,
        name: 'Snake Plant',
        cat:2,
        price: '103.96',
        quantity: '4',
        status: 'To Pay',
        review: 'Review',
        img: require('../../assets/images/Snake.png'),
        date:'21/06/2021',
    },
    {
        id: 6,
        name: 'Rattlesnake Plant',
        cat:2,
        price: '80.98',
        quantity: '2',
        status: 'Paid',
        review: 'Review',
        img: require('../../assets/images/Rattlesnake.png'),
        date:'13/07/2021',
    },
    {
        id: 7,
        name: 'Gasteria Plant',
        cat:2,
        price: '169.95',
        quantity: '5',
        status: 'To Pay',
        review: 'done',
        img: require('../../assets/images/Gasteria.png'),
        date:'15/10/2021',
    },
    {
        id: 8,
        name: 'Dragon Plant',
        cat:2,
        price: '75.99',
        quantity: '3',
        status: 'Pending',
        review: 'done',
        img: require('../../assets/images/dragon.png'),
        date:'29/12/2021',
    },
    {
        id: 9,
        name: 'Snake Plant',
        cat:3,
        price: '103.96',
        quantity: '4',
        status: 'To Pay',
        review: 'Review',
        img: require('../../assets/images/Snake.png'),
        date:'12/01/2022',
    },
    {
        id: 10,
        name: 'Rattlesnake Plant',
        cat:3,
        price: '80.98',
        quantity: '2',
        status: 'Paid',
        review: 'Review',
        img: require('../../assets/images/Rattlesnake.png'),
        date:'22/02/2022',
    },
    {
        id: 11,
        name: 'Gasteria Plant',
        cat:3,
        price: '169.95',
        quantity: '5',
        status: 'Paid',
        review: 'done',
        img: require('../../assets/images/Gasteria.png'),
        date:'13/05/2022',
    },
    {
        id: 12,
        name: 'Dragon Plant',
        cat:3,
        price: '75.99',
        quantity: '3',
        status: 'To Pay',
        review: 'done',
        img: require('../../assets/images/dragon.png'),
        date:'17/08/2022',
    },
]
export default orders;