const plants = [
    {
        id: 1,
        name: 'succulent Plant' ,
        price: '39.99',
        cat: '3',
        like: true,
        img: require('../../assets/images/succulent.png'),
        about: 'Succulent plants, also known as succulents or sometimes water storage plants, are plants that have some parts that are more than normally thickened and fleshy, usually to retain water in arid climates or soil conditions.',
    },
    {
        id: 2,
        name: 'Dragon Plant' ,
        price: '29.99',
        cat: '3',
        like: false,
        img: require('../../assets/images/dragon.png'),
        about: 'Dracaena marginata, more commonly known as a dragon tree, is an attractive plant with green sword-like, red-edged leaves. Native to Madagascar, the eye-catching spiky tree is known as a great entry plant for household gardeners',
    },
    {
        id: 3,
        name: 'Ravenea Plant' ,
        price: '25.99',
        cat: '2',
        like: true,
        img: require('../../assets/images/ravenea.png'),
        about: 'Ravenea rivularis, the majestic palm, or majesty palm, is a species of tree in the family Arecaceae. They generally grow to 10 to 12 feet tall and are often marketed in stores as a "houseplant" in a pot',
    },
    {
        id: 4,
        name: 'Cactus Plant' ,
        price: '35.99',
        cat: '2',
        like: true,
        img: require('../../assets/images/cactus.png'),
        about: 'The word cactus describes a type of desert plant that has thick, leafless stems covered in prickly spines or sharp spikes. Cactus plants are able to thrive in dry climates because they store water in their stems.',
    },
    {
        id: 5,
        name: 'Pothos Plant' ,
        price: '25.99',
        cat: '2',
        like: false,
        img: require('../../assets/images/money.png'),
        about: 'Pothos is an evergreen plant with thick, waxy, green, heart-shaped leaves with splashes of yellow. As a houseplant, it is commonly grown as a hanging plant. Pothos can climb by means of aerial roots',
    },
    {
        id: 6,
        name: 'Eucalyptus Plant' ,
        price: '15.99',
        cat: '2',
        like: true,
        img: require('../../assets/images/Eucalyptus.png'),
        about: 'This evergreen tree can grow to nearly 60 feet high in its natural Australian environment. But when planting eucalyptus in home gardens, it usually remains small at around 6 to 10 feet high.',
    },
    {
        id: 7,
        name: 'Philodendron Plant' ,
        price: '28.99',
        cat: '1',
        like: true,
        img: require('../../assets/images/Philodendron.png'),
        about: 'The Philodendron genus contains hundreds of species of beautiful foliage plants. Their leaves are typically large, green, and glossy, and philodendrons are great for adding a bit of their native tropical flair to your home.',
    },
    {
        id: 8,
        name: 'Snake Plant' ,
        price: '25.99',
        cat: 'POPULAR',
        like: false,
        img: require('../../assets/images/Snake.png'),
        about: 'Dracaena trifasciata, commonly known as the snake plant, is one of the most popular and hardy species of houseplants. Up until 2017, it was botanically classified as Sansevieria trifasciata.',
    },
    {
        id: 9,
        name: 'Rattlesnake Plant' ,
        price: '40.99',
        cat: 'INDOORS',
        like: true,
        img: require('../../assets/images/Rattlesnake.png'),
        about: 'In its native habitat, rattlesnake plant produces small yellow flowers in late spring. But as a houseplant, it is grown exclusively for its long, elegant, ornamental foliage, as it rarely blooms indoors.',
    },
    {
        id: 10,
        name: 'Gasteria Plant' ,
        price: '33.99',
        cat: '0',
        like: false,
        img: require('../../assets/images/Gasteria.png'),
        about: 'The genus is native to South Africa, where it grows in lightly shaded conditions. As a result, the plant tolerates lower light conditions than many other succulents do, making it a good option for a houseplant.',
    },
    {
        id: 11,
        name: 'Dragon Plant' ,
        price: '29.99',
        cat: '3',
        like: false,
        img: require('../../assets/images/dragon.png'),
        about: 'Dracaena marginata, more commonly known as a dragon tree, is an attractive plant with green sword-like, red-edged leaves. Native to Madagascar, the eye-catching spiky tree is known as a great entry plant for household gardeners',
    },
    {
        id: 12,
        name: 'Dragon Plant' ,
        price: '29.99',
        cat: '3',
        like: true,
        img: require('../../assets/images/dragon.png'),
        about: 'Dracaena marginata, more commonly known as a dragon tree, is an attractive plant with green sword-like, red-edged leaves. Native to Madagascar, the eye-catching spiky tree is known as a great entry plant for household gardeners',
    },
    {
        id: 13,
        name: 'Dragon Plant' ,
        price: '29.99',
        cat: '3',
        like: false,
        img: require('../../assets/images/dragon.png'),
        about: 'Dracaena marginata, more commonly known as a dragon tree, is an attractive plant with green sword-like, red-edged leaves. Native to Madagascar, the eye-catching spiky tree is known as a great entry plant for household gardeners',
    },
    {
        id: 14,
        name: 'Dragon Plant' ,
        price: '29.99',
        cat: '3',
        like: false,
        img: require('../../assets/images/dragon.png'),
        about: 'Dracaena marginata, more commonly known as a dragon tree, is an attractive plant with green sword-like, red-edged leaves. Native to Madagascar, the eye-catching spiky tree is known as a great entry plant for household gardeners',
    },
    {
        id: 15,
        name: 'Dragon Plant' ,
        price: '29.99',
        cat: '3',
        like: true,
        img: require('../../assets/images/dragon.png'),
        about: 'Dracaena marginata, more commonly known as a dragon tree, is an attractive plant with green sword-like, red-edged leaves. Native to Madagascar, the eye-catching spiky tree is known as a great entry plant for household gardeners',
    },
    {
        id: 16,
        name: 'Dragon Plant' ,
        price: '29.99',
        cat: '3',
        like: true,
        img: require('../../assets/images/dragon.png'),
        about: 'Dracaena marginata, more commonly known as a dragon tree, is an attractive plant with green sword-like, red-edged leaves. Native to Madagascar, the eye-catching spiky tree is known as a great entry plant for household gardeners',
    },
    {
        id: 17,
        name: 'Dragon Plant' ,
        price: '29.99',
        cat: '3',
        like: false,
        img: require('../../assets/images/dragon.png'),
        about: 'Dracaena marginata, more commonly known as a dragon tree, is an attractive plant with green sword-like, red-edged leaves. Native to Madagascar, the eye-catching spiky tree is known as a great entry plant for household gardeners',
    },
    {
        id: 18,
        name: 'Dragon Plant' ,
        price: '29.99',
        cat: '3',
        like: true,
        img: require('../../assets/images/dragon.png'),
        about: 'Dracaena marginata, more commonly known as a dragon tree, is an attractive plant with green sword-like, red-edged leaves. Native to Madagascar, the eye-catching spiky tree is known as a great entry plant for household gardeners',
    },
    {
        id: 19,
        name: 'Pothos Plant' ,
        price: '25.99',
        cat: '2',
        like: false,
        img: require('../../assets/images/money.png'),
        about: 'Pothos is an evergreen plant with thick, waxy, green, heart-shaped leaves with splashes of yellow. As a houseplant, it is commonly grown as a hanging plant. Pothos can climb by means of aerial roots',
    },
    {
        id: 20,
        name: 'Pothos Plant' ,
        price: '25.99',
        cat: '2',
        like: false,
        img: require('../../assets/images/money.png'),
        about: 'Pothos is an evergreen plant with thick, waxy, green, heart-shaped leaves with splashes of yellow. As a houseplant, it is commonly grown as a hanging plant. Pothos can climb by means of aerial roots',
    },
    {
        id: 21,
        name: 'Pothos Plant' ,
        price: '25.99',
        cat: '2',
        like: false,
        img: require('../../assets/images/money.png'),
        about: 'Pothos is an evergreen plant with thick, waxy, green, heart-shaped leaves with splashes of yellow. As a houseplant, it is commonly grown as a hanging plant. Pothos can climb by means of aerial roots',
    },
    {
        id: 22,
        name: 'Pothos Plant' ,
        price: '25.99',
        cat: '2',
        like: false,
        img: require('../../assets/images/money.png'),
        about: 'Pothos is an evergreen plant with thick, waxy, green, heart-shaped leaves with splashes of yellow. As a houseplant, it is commonly grown as a hanging plant. Pothos can climb by means of aerial roots',
    },
    {
        id: 23,
        name: 'Pothos Plant' ,
        price: '25.99',
        cat: '2',
        like: true,
        img: require('../../assets/images/money.png'),
        about: 'Pothos is an evergreen plant with thick, waxy, green, heart-shaped leaves with splashes of yellow. As a houseplant, it is commonly grown as a hanging plant. Pothos can climb by means of aerial roots',
    },
    {
        id: 24,
        name: 'Pothos Plant' ,
        price: '25.99',
        cat: '2',
        like: true,
        img: require('../../assets/images/money.png'),
        about: 'Pothos is an evergreen plant with thick, waxy, green, heart-shaped leaves with splashes of yellow. As a houseplant, it is commonly grown as a hanging plant. Pothos can climb by means of aerial roots',
    },
    {
        id: 25,
        name: 'Pothos Plant' ,
        price: '25.99',
        cat: '2',
        like: false,
        img: require('../../assets/images/money.png'),
        about: 'Pothos is an evergreen plant with thick, waxy, green, heart-shaped leaves with splashes of yellow. As a houseplant, it is commonly grown as a hanging plant. Pothos can climb by means of aerial roots',
    },
    {
        id: 26,
        name: 'Pothos Plant' ,
        price: '25.99',
        cat: '2',
        like: true,
        img: require('../../assets/images/money.png'),
        about: 'Pothos is an evergreen plant with thick, waxy, green, heart-shaped leaves with splashes of yellow. As a houseplant, it is commonly grown as a hanging plant. Pothos can climb by means of aerial roots',
    },
    {
        id: 27,
        name: 'Pothos Plant' ,
        price: '25.99',
        cat: '2',
        like: false,
        img: require('../../assets/images/money.png'),
        about: 'Pothos is an evergreen plant with thick, waxy, green, heart-shaped leaves with splashes of yellow. As a houseplant, it is commonly grown as a hanging plant. Pothos can climb by means of aerial roots',
    },
    {
        id: 28,
        name: 'Pothos Plant' ,
        price: '25.99',
        cat: '2',
        like: true,
        img: require('../../assets/images/money.png'),
        about: 'Pothos is an evergreen plant with thick, waxy, green, heart-shaped leaves with splashes of yellow. As a houseplant, it is commonly grown as a hanging plant. Pothos can climb by means of aerial roots',
    },
    {
        id: 29,
        name: 'Philodendron Plant' ,
        price: '28.99',
        cat: '1',
        like: true,
        img: require('../../assets/images/Philodendron.png'),
        about: 'The Philodendron genus contains hundreds of species of beautiful foliage plants. Their leaves are typically large, green, and glossy, and philodendrons are great for adding a bit of their native tropical flair to your home.',
    },
    {
        id: 30,
        name: 'Snake Plant' ,
        price: '25.99',
        cat: '1',
        like: false,
        img: require('../../assets/images/Snake.png'),
        about: 'Dracaena trifasciata, commonly known as the snake plant, is one of the most popular and hardy species of houseplants. Up until 2017, it was botanically classified as Sansevieria trifasciata.',
    },
    {
        id: 31,
        name: 'Philodendron Plant' ,
        price: '28.99',
        cat: '1',
        like: true,
        img: require('../../assets/images/Philodendron.png'),
        about: 'The Philodendron genus contains hundreds of species of beautiful foliage plants. Their leaves are typically large, green, and glossy, and philodendrons are great for adding a bit of their native tropical flair to your home.',
    },
    {
        id: 32,
        name: 'Snake Plant' ,
        price: '25.99',
        cat: '1',
        like: false,
        img: require('../../assets/images/Snake.png'),
        about: 'Dracaena trifasciata, commonly known as the snake plant, is one of the most popular and hardy species of houseplants. Up until 2017, it was botanically classified as Sansevieria trifasciata.',
    },
    {
        id: 33,
        name: 'Philodendron Plant' ,
        price: '28.99',
        cat: '1',
        like: true,
        img: require('../../assets/images/Philodendron.png'),
        about: 'The Philodendron genus contains hundreds of species of beautiful foliage plants. Their leaves are typically large, green, and glossy, and philodendrons are great for adding a bit of their native tropical flair to your home.',
    },
    {
        id: 34,
        name: 'Snake Plant' ,
        price: '25.99',
        cat: '1',
        like: true,
        img: require('../../assets/images/Snake.png'),
        about: 'Dracaena trifasciata, commonly known as the snake plant, is one of the most popular and hardy species of houseplants. Up until 2017, it was botanically classified as Sansevieria trifasciata.',
    },
    {
        id: 35,
        name: 'Philodendron Plant' ,
        price: '28.99',
        cat: '1',
        like: false,
        img: require('../../assets/images/Philodendron.png'),
        about: 'The Philodendron genus contains hundreds of species of beautiful foliage plants. Their leaves are typically large, green, and glossy, and philodendrons are great for adding a bit of their native tropical flair to your home.',
    },
    {
        id: 36,
        name: 'Snake Plant' ,
        price: '25.99',
        cat: '1',
        like: false,
        img: require('../../assets/images/Snake.png'),
        about: 'Dracaena trifasciata, commonly known as the snake plant, is one of the most popular and hardy species of houseplants. Up until 2017, it was botanically classified as Sansevieria trifasciata.',
    },
    {
        id: 37,
        name: 'Rattlesnake Plant' ,
        price: '40.99',
        cat: '0',
        like: true,
        img: require('../../assets/images/Rattlesnake.png'),
        about: 'In its native habitat, rattlesnake plant produces small yellow flowers in late spring. But as a houseplant, it is grown exclusively for its long, elegant, ornamental foliage, as it rarely blooms indoors.',
    },
    {
        id: 38,
        name: 'Gasteria Plant' ,
        price: '33.99',
        cat: '0',
        like: false,
        img: require('../../assets/images/Gasteria.png'),
        about: 'The genus is native to South Africa, where it grows in lightly shaded conditions. As a result, the plant tolerates lower light conditions than many other succulents do, making it a good option for a houseplant.',
    },
    {
        id: 39,
        name: 'Rattlesnake Plant' ,
        price: '40.99',
        cat: '0',
        like: false,
        img: require('../../assets/images/Rattlesnake.png'),
        about: 'In its native habitat, rattlesnake plant produces small yellow flowers in late spring. But as a houseplant, it is grown exclusively for its long, elegant, ornamental foliage, as it rarely blooms indoors.',
    },
    {
        id: 40,
        name: 'Gasteria Plant' ,
        price: '33.99',
        cat: '0',
        like: false,
        img: require('../../assets/images/Gasteria.png'),
        about: 'The genus is native to South Africa, where it grows in lightly shaded conditions. As a result, the plant tolerates lower light conditions than many other succulents do, making it a good option for a houseplant.',
    },
    {
        id: 41,
        name: 'Rattlesnake Plant' ,
        price: '40.99',
        cat: '0',
        like: true,
        img: require('../../assets/images/Rattlesnake.png'),
        about: 'In its native habitat, rattlesnake plant produces small yellow flowers in late spring. But as a houseplant, it is grown exclusively for its long, elegant, ornamental foliage, as it rarely blooms indoors.',
    },
    {
        id: 42,
        name: 'Gasteria Plant' ,
        price: '33.99',
        cat: '0',
        like: false,
        img: require('../../assets/images/Gasteria.png'),
        about: 'The genus is native to South Africa, where it grows in lightly shaded conditions. As a result, the plant tolerates lower light conditions than many other succulents do, making it a good option for a houseplant.',
    },
    {
        id: 43,
        name: 'Rattlesnake Plant' ,
        price: '40.99',
        cat: '0',
        like: false,
        img: require('../../assets/images/Rattlesnake.png'),
        about: 'In its native habitat, rattlesnake plant produces small yellow flowers in late spring. But as a houseplant, it is grown exclusively for its long, elegant, ornamental foliage, as it rarely blooms indoors.',
    },
    {
        id: 44,
        name: 'Gasteria Plant' ,
        price: '33.99',
        cat: '0',
        like: false,
        img: require('../../assets/images/Gasteria.png'),
        about: 'The genus is native to South Africa, where it grows in lightly shaded conditions. As a result, the plant tolerates lower light conditions than many other succulents do, making it a good option for a houseplant.',
    },
    {
        id: 45,
        name: 'Rattlesnake Plant' ,
        price: '40.99',
        cat: '0',
        like: true,
        img: require('../../assets/images/Rattlesnake.png'),
        about: 'In its native habitat, rattlesnake plant produces small yellow flowers in late spring. But as a houseplant, it is grown exclusively for its long, elegant, ornamental foliage, as it rarely blooms indoors.',
    },
    {
        id: 46,
        name: 'Gasteria Plant' ,
        price: '33.99',
        cat: '0',
        like: false,
        img: require('../../assets/images/Gasteria.png'),
        about: 'The genus is native to South Africa, where it grows in lightly shaded conditions. As a result, the plant tolerates lower light conditions than many other succulents do, making it a good option for a houseplant.',
    },
    {
        id: 47,
        name: 'Rattlesnake Plant' ,
        price: '40.99',
        cat: '0',
        like: false,
        img: require('../../assets/images/Rattlesnake.png'),
        about: 'In its native habitat, rattlesnake plant produces small yellow flowers in late spring. But as a houseplant, it is grown exclusively for its long, elegant, ornamental foliage, as it rarely blooms indoors.',
    },
    {
        id: 48,
        name: 'Gasteria Plant' ,
        price: '33.99',
        cat: '0',
        like: true,
        img: require('../../assets/images/Gasteria.png'),
        about: 'The genus is native to South Africa, where it grows in lightly shaded conditions. As a result, the plant tolerates lower light conditions than many other succulents do, making it a good option for a houseplant.',
    },
    {
        id: 49,
        name: 'Rattlesnake Plant' ,
        price: '40.99',
        cat: '0',
        like: true,
        img: require('../../assets/images/Rattlesnake.png'),
        about: 'In its native habitat, rattlesnake plant produces small yellow flowers in late spring. But as a houseplant, it is grown exclusively for its long, elegant, ornamental foliage, as it rarely blooms indoors.',
    },
    {
        id: 50,
        name: 'Gasteria Plant' ,
        price: '33.99',
        cat: '0',
        like: true,
        img: require('../../assets/images/Gasteria.png'),
        about: 'The genus is native to South Africa, where it grows in lightly shaded conditions. As a result, the plant tolerates lower light conditions than many other succulents do, making it a good option for a houseplant.',
    },
]

export default plants;